const BASE = process.env.SCREEN_URL ?? 'http://127.0.0.1:5173'
import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } })
page.on('pageerror', (e) => console.log('[pageerror]', String(e).slice(0, 200)))
await page.addInitScript(() => localStorage.setItem('drone-screen-token', 'mock-token-shot'))
await page.goto(BASE + '/', { waitUntil: 'networkidle' })
await page.waitForTimeout(3000)
const btn = page.locator('button.center-map__disaster').first()
console.log('初始按钮:', await btn.textContent(), '| disabled:', await btn.isDisabled())
await btn.click()
await page.waitForTimeout(3500)
console.log('点击后 active:', await page.evaluate(() => window.__DISASTER?.flood?.value !== null))
const resolveBtn = page.locator('button.center-map__disaster--resolve')
console.log('结束演练按钮出现:', await resolveBtn.count() === 1 ? 'OK' : 'FAIL')
await resolveBtn.click()
await page.waitForTimeout(1500)
console.log('结束后 active:', await page.evaluate(() => window.__DISASTER?.flood?.value !== null))
console.log('模拟洪灾按钮恢复:', !(await btn.isDisabled()) ? 'OK' : 'FAIL')
// 再点一次确认可重复演练
await btn.click()
await page.waitForTimeout(2500)
console.log('再次模拟成功:', await page.evaluate(() => window.__DISASTER?.flood?.value !== null) ? 'OK' : 'FAIL')
await browser.close()
